version: "3.1"
services:
  web:
    image: ${WEB_IMAGE}
    restart: always
    volumes:
      - ${ROOT_DIR}:/app
      - ${SERVER_CONF_DIR}:/etc/apache2/sites-available
      - ${LOGS_DIR}:/var/log/apache2
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

  db:
    image: ${DB_IMAGE}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${DB_STORAGE_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"


networks:
  default:
    external:
      name: amp-yii_temp