version: "3.1"
services:

  web:
    image: sreine/yii2-apcu
    restart: always
    volumes:
      - ./yii:/app
      - ./data/conf:/etc/apache2/sites-available
      - ./data/logs:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./secret/dev.env
    ports:
      - "3306:3306"


networks:
  default:
    external:
      name: amp-yii